var R=require("../../../chunks/ssr/[turbopack]_runtime.js")("server/app/[lang]/bursdag/page.js")
R.c("server/chunks/ssr/[root-of-the-server]__1ai1w1c._.js")
R.c("server/chunks/ssr/node_modules_next_dist_0xaccoz._.js")
R.c("server/chunks/ssr/node_modules_next_dist_esm_build_templates_app-page_0hxd-t-.js")
R.c("server/chunks/ssr/[root-of-the-server]__0t05e2h._.js")
R.c("server/chunks/ssr/[root-of-the-server]__0kl59ms._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_0wpq8j3._.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_forbidden_0symwr9.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_unauthorized_0l_sp0x.js")
R.c("server/chunks/ssr/node_modules_next_dist_client_components_builtin_global-error_0-o-goa.js")
R.c("server/chunks/ssr/[root-of-the-server]__1hbmn0m._.js")
R.c("server/chunks/ssr/_1bl60zx._.js")
R.c("server/chunks/ssr/_next-internal_server_app_[lang]_bursdag_page_actions_1jzlaqo.js")
R.m(37438)
module.exports=R.m(37438).exports
