// This file is generated automatically by Next.js
// Do not edit this file manually

type AppRoutes = "/[lang]" | "/[lang]/bedrift" | "/[lang]/bursdag" | "/[lang]/gavekort" | "/[lang]/medlemskap" | "/[lang]/personvern" | "/[lang]/polf" | "/[lang]/praktisk" | "/[lang]/veien-til-golf" | "/[lang]/vilkar" | "/[lang]/vinterturnering" | "/[lang]/vip-losjen"
type PageRoutes = never
type LayoutRoutes = "/[lang]"
type RedirectRoutes = never
type RewriteRoutes = never
type Routes = AppRoutes | PageRoutes | LayoutRoutes | RedirectRoutes | RewriteRoutes


interface ParamMap {
  "/[lang]": { "lang": string; }
  "/[lang]/bedrift": { "lang": string; }
  "/[lang]/bursdag": { "lang": string; }
  "/[lang]/gavekort": { "lang": string; }
  "/[lang]/medlemskap": { "lang": string; }
  "/[lang]/personvern": { "lang": string; }
  "/[lang]/polf": { "lang": string; }
  "/[lang]/praktisk": { "lang": string; }
  "/[lang]/veien-til-golf": { "lang": string; }
  "/[lang]/vilkar": { "lang": string; }
  "/[lang]/vinterturnering": { "lang": string; }
  "/[lang]/vip-losjen": { "lang": string; }
}


export type ParamsOf<Route extends Routes> = ParamMap[Route]

interface LayoutSlotMap {
  "/[lang]": never
}


export type { AppRoutes, PageRoutes, LayoutRoutes, RedirectRoutes, RewriteRoutes, ParamMap }

declare global {
  /**
   * Props for Next.js App Router page components
   * @example
   * ```tsx
   * export default function Page(props: PageProps<'/blog/[slug]'>) {
   *   const { slug } = await props.params
   *   return <div>Blog post: {slug}</div>
   * }
   * ```
   */
  interface PageProps<AppRoute extends AppRoutes> {
    params: Promise<ParamMap[AppRoute]>
    searchParams: Promise<Record<string, string | string[] | undefined>>
  }

  /**
   * Props for Next.js App Router layout components
   * @example
   * ```tsx
   * export default function Layout(props: LayoutProps<'/dashboard'>) {
   *   return <div>{props.children}</div>
   * }
   * ```
   */
  type LayoutProps<LayoutRoute extends LayoutRoutes> = {
    params: Promise<ParamMap[LayoutRoute]>
    children: React.ReactNode
  } & {
    [K in LayoutSlotMap[LayoutRoute]]: React.ReactNode
  }
}
